// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.tsx";
import * as $index from "./routes/index.tsx";
import * as $CookieNotice from "./islands/CookieNotice.tsx";
import * as $RichMessageEditor from "./islands/RichMessageEditor.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.tsx": $_middleware,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/CookieNotice.tsx": $CookieNotice,
    "./islands/RichMessageEditor.tsx": $RichMessageEditor,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
